"""add_index_to_discarded_at

Revision ID: 9d1295abfa5b
Revises: 5de2e323d15d
Create Date: 2026-01-14 06:38:29.052939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d1295abfa5b'
down_revision: Union[str, None] = '5de2e323d15d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.create_index(op.f('ix_videos_discarded_at'), 'videos', ['discarded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_discarded_at'), table_name='videos')
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    # ### end Alembic commands ###
