"""add_explicit_index_to_youtube_video_id

Revision ID: 63e6b77c0da0
Revises: 9d1295abfa5b
Create Date: 2026-01-19 22:14:51.986701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63e6b77c0da0'
down_revision: Union[str, None] = '9d1295abfa5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_videos_youtube_video_id'), 'videos', ['youtube_video_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_youtube_video_id'), table_name='videos')
    # ### end Alembic commands ###
